### ISSUE TITLE
Pendencias - 4ª Avaliação Consulta COVID

### ISSUE THREAD

**Issue by silviana-faria** [transparencia-mg/especificacoes-portal-transparencia#31]
[Plano de ação 3ª avaliação](https://drive.google.com/drive/u/1/folders/1Wx3pCFwJWG1moH9Y9J1dEj9a8gB4fgsW)

## Soraia

- [ ] Status da entrega do item de material/ serviço - Verificar com a SEPLAG se existe essa informação no Portal de Compras - Conversar com Francisco **Ver issues #32**

- [x] Categoria Legislação - Item Controle - Verificar com a Nicolle por qual motivo ela classificou esse item como "zero"", atualmente temos duas resoluções CGE que tratam do assunto.

- [ ] Aprovar conteúdo que será disponibilizado na consulta COVID [legislação e normativos](https://github.com/transparencia-mg/transparencia-mg-estatico/blob/master/content/covid-19/legislacao-normativos.md); [Doações](https://github.com/transparencia-mg/transparencia-mg-estatico/blob/master/content/covid-19/doacoes.md); [Medidas de estímulo econômico e proteção social](https://github.com/transparencia-mg/transparencia-mg-estatico/blob/master/content/covid-19/medidas-estimulo-economico-protecao-social.md); [Ouvidoria](https://github.com/transparencia-mg/transparencia-mg-estatico/blob/master/content/covid-19/ouvidoria-coronavirus.md); [Lei de Acesso à Informação](https://github.com/transparencia-mg/transparencia-mg-estatico/blob/master/content/covid-19/lei-acesso-informacao.md)

- [x] Solicitar a ASCOM CGE que crie no site da CGE um repositório específico com a legislação afeta ao assunto. **Conforme orientação da Nicolle é melhor inserir as legislações no próprio Portal da Transparência**

- [x] Solicitar a SEDESE que crie no site um repositório específico com a legislação afeta ao assunto e disponibilize os relatórios de medidas de estímulo social para  utilizarmos apenas os links. #30 - **Conforme orientação da Nicolle é melhor inserir as legislações no próprio Portal da Transparência.**

- [ ] Solicitar a SEDESE que disponibilize  os relatórios de medidas de estímulo social no menu transparência do site do órgão com identificação #30

- [x] Solicitar a SEF e SEDE que crie no site um repositório específico com a legislação afeta ao assunto e disponibilize os relatórios de medidas de estímulo econômico para  utilizarmos apenas os links #28. **Conforme orientação da Nicolle é para disponibilizar no Portal o link do site da SEDE para cumprir o quesito relatórios de medidas de estímulo econômico**

- [ ] Alinhar com o Gabinete Militar a frequência de envio da planilha de doações. E solicitar mais planilhas para definirmos como transpor essa informações para um conjunto de Dados.

- [ ] Solicitar a DTP o relatório estatístico dos pedidos de acesso afetos a COVID-19

- [x] Comunicar a Nicolle sobre os dashboards.

**Comment by silviana-faria** [comment]
## Silviana

- [ ] Criar conjunto de dado da planilha Doações

- [ ] Incluir alterações em produção - aguardar aprovação para inclusão

## Francisco

- [ ] Verificar a possibilidade de colocar dashboards no Portal de Dados Abertos
